import { router } from 'expo-router';
import { Check, ChevronLeft, Copy, KeyRound, Plus, Trash2, X } from 'lucide-react-native';
import { useRef, useState } from 'react';
import { ActivityIndicator, Alert, Modal, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import * as Clipboard from 'expo-clipboard';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { adminConfigState } from '@/src/store/admin-config';
import { createUserApiKey, deleteUserApiKey, listAvailableGroups, listUserApiKeys, updateUserApiKey, type UserApiKey } from '@/src/services/user';
import { humanizeApiError, redactSecret } from '@/src/lib/admin-fetch';
import { formatOptionalMoney, formatOptionalNumber } from '@/src/lib/formatters';
import { newIdempotencyKey } from '@/src/lib/idempotency';
import { theme } from '@/src/theme';
import { useSnapshot } from 'valtio/react';

export default function UserKeys() {
  const config = useSnapshot(adminConfigState); const queryClient = useQueryClient(); const createKey = useRef(''); const actionKeys = useRef<Record<string, string>>({});
  const [open, setOpen] = useState(false); const [name, setName] = useState(''); const [groupId, setGroupId] = useState<number | undefined>();
  const keys = useQuery({ queryKey: ['user-api-keys'], queryFn: () => listUserApiKeys(), enabled: Boolean(config.accessToken) });
  const groups = useQuery({ queryKey: ['user-available-groups'], queryFn: listAvailableGroups, enabled: open && Boolean(config.accessToken) });
  const create = useMutation({ mutationFn: () => { if (!createKey.current) createKey.current = newIdempotencyKey('user-key-create'); return createUserApiKey({ name: name.trim(), group_id: groupId }, createKey.current); }, onSuccess: (key) => { createKey.current = ''; setOpen(false); setName(''); setGroupId(undefined); void queryClient.invalidateQueries({ queryKey: ['user-api-keys'] }); Alert.alert('API 密钥已创建', key.key ? `请立即保存：${key.key}` : '服务端已创建密钥。'); } });
  const toggle = useMutation({ mutationFn: ({ key, status, idempotencyKey }: { key: UserApiKey; status: 'active' | 'inactive'; idempotencyKey: string }) => updateUserApiKey(key.id, { status }, idempotencyKey), onSuccess: (_result, input) => { delete actionKeys.current[`toggle-${input.key.id}`]; void queryClient.invalidateQueries({ queryKey: ['user-api-keys'] }); } });
  const remove = useMutation({ mutationFn: ({ id, idempotencyKey }: { id: number; idempotencyKey: string }) => deleteUserApiKey(id, idempotencyKey), onSuccess: (_result, input) => { delete actionKeys.current[`delete-${input.id}`]; void queryClient.invalidateQueries({ queryKey: ['user-api-keys'] }); } });
  const items = keys.data?.items ?? [];
  function confirmDelete(key: UserApiKey) { Alert.alert('删除 API 密钥', `确认删除「${key.name}」？删除后不可恢复。`, [{ text: '取消', style: 'cancel' }, { text: '删除', style: 'destructive', onPress: () => { const scope = `delete-${key.id}`; if (!actionKeys.current[scope]) actionKeys.current[scope] = newIdempotencyKey(`user-key-delete-${key.id}`); remove.mutate({ id: key.id, idempotencyKey: actionKeys.current[scope] }); } }]); }
  return <View style={{ flex: 1, backgroundColor: theme.page }}><ScrollView contentContainerStyle={{ padding: 20, gap: 14 }}>
    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12 }}><Pressable onPress={() => router.back()} style={{ padding: 8 }}><ChevronLeft color={theme.text} size={22} /></Pressable><View style={{ flex: 1 }}><Text style={{ color: theme.text, fontSize: 25, fontWeight: '900' }}>API 密钥</Text><Text style={{ color: theme.subtext, marginTop: 3 }}>仅显示当前账号的真实服务端密钥</Text></View><Pressable accessibilityRole="button" accessibilityLabel="create-api-key" onPress={() => setOpen(true)} style={{ width: 42, height: 42, borderRadius: 14, backgroundColor: theme.primary, alignItems: 'center', justifyContent: 'center' }}><Plus color="#fff" size={20} /></Pressable></View>
    {keys.error ? <Text style={{ color: theme.danger }}>{humanizeApiError(keys.error)}</Text> : null}
    {keys.isLoading ? <ActivityIndicator color={theme.primary} style={{ marginTop: 30 }} /> : items.length ? items.map((key) => <KeyCard key={key.id} apiKey={key} onCopy={() => void Clipboard.setStringAsync(key.key)} onToggle={() => { const scope = `toggle-${key.id}`; if (!actionKeys.current[scope]) actionKeys.current[scope] = newIdempotencyKey(`user-key-toggle-${key.id}`); toggle.mutate({ key, status: key.status === 'active' ? 'inactive' : 'active', idempotencyKey: actionKeys.current[scope] }); }} onDelete={() => confirmDelete(key)} />) : <View style={{ backgroundColor: theme.card, borderRadius: 18, padding: 28, alignItems: 'center' }}><KeyRound color={theme.faint} size={28} /><Text style={{ color: theme.subtext, marginTop: 12 }}>还没有 API 密钥</Text><Text style={{ color: theme.faint, fontSize: 12, marginTop: 5 }}>创建后即可连接 Vexlune Hub API</Text></View>}
  </ScrollView>
  <Modal transparent visible={open} animationType="slide" onRequestClose={() => setOpen(false)}><View style={{ flex: 1, justifyContent: 'flex-end', backgroundColor: '#00000088' }}><View style={{ backgroundColor: theme.card, borderTopLeftRadius: 26, borderTopRightRadius: 26, padding: 20 }}><View style={{ flexDirection: 'row', alignItems: 'center' }}><Text style={{ color: theme.text, fontWeight: '900', fontSize: 20, flex: 1 }}>创建 API 密钥</Text><Pressable onPress={() => setOpen(false)}><X color={theme.subtext} size={21} /></Pressable></View><Text style={{ color: theme.subtext, fontSize: 12, marginTop: 6 }}>密钥只会在服务端返回时展示一次，请妥善保存。</Text><TextInput accessibilityLabel="api-key-name" value={name} onChangeText={setName} placeholder="名称，例如：我的开发环境" placeholderTextColor={theme.faint} style={{ color: theme.text, backgroundColor: theme.cardRaised, borderRadius: 14, padding: 14, marginTop: 18 }} />{groups.data?.length ? <><Text style={{ color: theme.subtext, fontSize: 12, marginTop: 15 }}>分组（可选）</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, paddingVertical: 8 }}>{groups.data.map((group) => <Pressable key={group.id} onPress={() => setGroupId(group.id)} style={{ borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8, backgroundColor: groupId === group.id ? theme.primary : theme.cardRaised }}><Text style={{ color: groupId === group.id ? '#fff' : theme.subtext, fontSize: 12 }}>{group.name}</Text></Pressable>)}</ScrollView></> : null}{create.error ? <Text style={{ color: theme.danger, fontSize: 12, marginTop: 10 }}>{humanizeApiError(create.error)}</Text> : null}<Pressable disabled={!name.trim() || create.isPending} onPress={() => create.mutate()} style={{ marginTop: 17, borderRadius: 15, paddingVertical: 14, backgroundColor: !name.trim() || create.isPending ? theme.muted : theme.primary, alignItems: 'center' }}><Text style={{ color: '#fff', fontWeight: '900' }}>{create.isPending ? '创建中…' : '创建密钥'}</Text></Pressable></View></View></Modal>
  </View>;
}

function KeyCard({ apiKey, onCopy, onToggle, onDelete }: { apiKey: UserApiKey; onCopy: () => void; onToggle: () => void; onDelete: () => void }) {
  const active = apiKey.status === 'active';
  return <View style={{ backgroundColor: theme.card, borderColor: theme.border, borderWidth: 1, borderRadius: 18, padding: 16 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}><View style={{ width: 38, height: 38, borderRadius: 12, backgroundColor: active ? theme.successSoft : theme.cardRaised, alignItems: 'center', justifyContent: 'center' }}><KeyRound color={active ? theme.success : theme.faint} size={18} /></View><View style={{ flex: 1 }}><Text style={{ color: theme.text, fontWeight: '900' }}>{apiKey.name}</Text><Text selectable style={{ color: theme.subtext, fontSize: 12, marginTop: 4 }}>{redactSecret(apiKey.key || '', 6)}</Text></View><View style={{ borderRadius: 999, paddingHorizontal: 9, paddingVertical: 5, backgroundColor: active ? theme.successSoft : theme.cardRaised }}><Text style={{ color: active ? theme.success : theme.faint, fontSize: 11, fontWeight: '800' }}>{active ? '启用' : '停用'}</Text></View></View><View style={{ height: 1, backgroundColor: theme.border, marginVertical: 14 }} /><View style={{ flexDirection: 'row', gap: 12 }}><Stat label="已用额度" value={`${formatOptionalMoney(apiKey.quota_used)}${apiKey.quota === null || apiKey.quota === undefined ? '' : ` / ${formatOptionalMoney(apiKey.quota)}`} `} /><Stat label="近 5 小时" value={formatOptionalMoney(apiKey.usage_5h)} /><Stat label="并发" value={formatOptionalNumber(apiKey.current_concurrency)} /></View><View style={{ flexDirection: 'row', gap: 8, marginTop: 14 }}><Pressable onPress={onCopy} style={{ flex: 1, borderRadius: 11, backgroundColor: theme.primarySoft, paddingVertical: 10, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 6 }}><Copy color={theme.primary} size={15} /><Text style={{ color: theme.primary, fontSize: 12, fontWeight: '800' }}>复制</Text></Pressable><Pressable onPress={onToggle} style={{ flex: 1, borderRadius: 11, backgroundColor: theme.cardRaised, paddingVertical: 10, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 6 }}>{active ? <X color={theme.warning} size={15} /> : <Check color={theme.success} size={15} />}<Text style={{ color: theme.subtext, fontSize: 12, fontWeight: '800' }}>{active ? '停用' : '启用'}</Text></Pressable><Pressable onPress={onDelete} style={{ borderRadius: 11, backgroundColor: theme.dangerSoft, paddingHorizontal: 15, paddingVertical: 10, alignItems: 'center', justifyContent: 'center' }}><Trash2 color={theme.danger} size={15} /></Pressable></View></View>;
}
function Stat({ label, value }: { label: string; value: string }) { return <View style={{ flex: 1 }}><Text style={{ color: theme.faint, fontSize: 10 }}>{label}</Text><Text style={{ color: theme.text, fontWeight: '800', fontSize: 12, marginTop: 4 }} numberOfLines={1}>{value}</Text></View>; }
