import { router } from 'expo-router';
import { Bell, ChevronLeft, Check } from 'lucide-react-native';
import { useState } from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, Text, View } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { adminConfigState } from '@/src/store/admin-config';
import { listUserAnnouncements, markAnnouncementRead, type UserAnnouncement } from '@/src/services/user';
import { humanizeApiError } from '@/src/lib/admin-fetch';
import { theme } from '@/src/theme';
const { useSnapshot } = require('valtio/react');

export default function UserAnnouncements() {
  const config = useSnapshot(adminConfigState); const client = useQueryClient(); const [selected, setSelected] = useState<UserAnnouncement>();
  const query = useQuery({ queryKey: ['user-announcements'], queryFn: listUserAnnouncements, enabled: Boolean(config.accessToken) });
  const read = useMutation({ mutationFn: (id: number) => markAnnouncementRead(id), onSuccess: () => void client.invalidateQueries({ queryKey: ['user-announcements'] }) });
  const items = query.data ?? [];
  function open(item: UserAnnouncement) { setSelected(item); if (!item.read_at) read.mutate(item.id); }
  return <View style={{ flex: 1, backgroundColor: theme.page }}><ScrollView contentContainerStyle={{ padding: 20, gap: 14 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 12 }}><Pressable onPress={() => router.back()} style={{ padding: 8 }}><ChevronLeft color={theme.text} size={22} /></Pressable><View><Text style={{ color: theme.text, fontSize: 25, fontWeight: '900' }}>公告</Text><Text style={{ color: theme.subtext, marginTop: 3 }}>来自 Vexlune Hub 服务端的通知</Text></View></View>{query.error ? <Text style={{ color: theme.danger }}>{humanizeApiError(query.error)}</Text> : null}{query.isLoading ? <ActivityIndicator color={theme.primary} style={{ marginTop: 30 }} /> : items.length ? items.map((item) => <Pressable key={item.id} onPress={() => open(item)} style={{ backgroundColor: theme.card, borderRadius: 18, borderWidth: 1, borderColor: theme.border, padding: 16 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}><View style={{ width: 36, height: 36, borderRadius: 11, backgroundColor: item.read_at ? theme.cardRaised : theme.primarySoft, alignItems: 'center', justifyContent: 'center' }}>{item.read_at ? <Check color={theme.faint} size={17} /> : <Bell color={theme.primary} size={17} />}</View><View style={{ flex: 1 }}><Text style={{ color: theme.text, fontWeight: '900' }} numberOfLines={1}>{item.title}</Text><Text style={{ color: theme.subtext, fontSize: 11, marginTop: 4 }}>{item.created_at ? new Date(item.created_at).toLocaleDateString('zh-CN') : '--'}{item.read_at ? ' · 已读' : ' · 未读'}</Text></View></View><Text style={{ color: theme.subtext, lineHeight: 19, marginTop: 12 }} numberOfLines={2}>{item.content}</Text></Pressable>) : <View style={{ padding: 30, alignItems: 'center' }}><Bell color={theme.faint} size={28} /><Text style={{ color: theme.subtext, marginTop: 10 }}>暂无公告</Text></View>}</ScrollView><Modal transparent visible={Boolean(selected)} animationType="slide" onRequestClose={() => setSelected(undefined)}><View style={{ flex: 1, justifyContent: 'flex-end', backgroundColor: '#00000088' }}><View style={{ maxHeight: '82%', backgroundColor: theme.card, borderTopLeftRadius: 26, borderTopRightRadius: 26, padding: 20 }}>{selected ? <><Text style={{ color: theme.text, fontSize: 20, fontWeight: '900' }}>{selected.title}</Text><Text style={{ color: theme.faint, fontSize: 11, marginTop: 6 }}>{selected.created_at ? new Date(selected.created_at).toLocaleString('zh-CN') : '--'}</Text><ScrollView style={{ marginTop: 18 }}><Text style={{ color: theme.subtext, lineHeight: 22 }}>{selected.content}</Text></ScrollView><Pressable onPress={() => setSelected(undefined)} style={{ marginTop: 17, borderRadius: 14, backgroundColor: theme.primary, paddingVertical: 13, alignItems: 'center' }}><Text style={{ color: '#fff', fontWeight: '900' }}>关闭</Text></Pressable></> : null}</View></View></Modal></View>;
}
