import { router } from 'expo-router';
import { CheckCircle2, ChevronLeft, CreditCard, RefreshCw, XCircle } from 'lucide-react-native';
import { useRef, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, Text, View } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { adminConfigState } from '@/src/store/admin-config';
import { cancelPaymentOrder, createPaymentOrder, getCheckoutInfo, listPaymentOrders, verifyPaymentOrder, type CheckoutPlan, type PaymentOrder } from '@/src/services/user';
import { humanizeApiError } from '@/src/lib/admin-fetch';
import { theme } from '@/src/theme';
const { useSnapshot } = require('valtio/react');

export default function UserBilling() {
  const config = useSnapshot(adminConfigState); const client = useQueryClient(); const [plan, setPlan] = useState<CheckoutPlan>(); const createKey = useRef('');
  const checkout = useQuery({ queryKey: ['payment-checkout-info'], queryFn: getCheckoutInfo, enabled: Boolean(config.accessToken) });
  const orders = useQuery({ queryKey: ['payment-orders'], queryFn: () => listPaymentOrders(), enabled: Boolean(config.accessToken) });
  const create = useMutation({ mutationFn: () => { if (!plan) throw new Error('请选择一个套餐'); const paymentType = methods[0]; if (!paymentType) throw new Error('当前没有可用的支付方式'); if (!createKey.current) createKey.current = `mobile-payment-${Date.now()}-${Math.random().toString(36).slice(2)}`; return createPaymentOrder({ amount: plan.price, plan_id: plan.id, order_type: 'subscription', payment_type: paymentType }, createKey.current); }, onSuccess: (order) => { createKey.current = ''; void client.invalidateQueries({ queryKey: ['payment-orders'] }); Alert.alert('订单已创建', `订单号：${order.out_trade_no || order.id}\n状态：${order.status || '待支付'}\n请按服务端返回的支付信息完成付款。`); } });
  const cancel = useMutation({ mutationFn: (id: number) => cancelPaymentOrder(id), onSuccess: () => void client.invalidateQueries({ queryKey: ['payment-orders'] }) });
  const verify = useMutation({ mutationFn: (order: PaymentOrder) => verifyPaymentOrder(order.out_trade_no), onSuccess: () => void client.invalidateQueries({ queryKey: ['payment-orders'] }) });
  const methods = Object.entries(checkout.data?.methods ?? {}).filter(([, value]) => value?.enabled !== false).map(([key]) => key);
  const actionError = cancel.error || verify.error;
  return <View style={{ flex: 1, backgroundColor: theme.page }}><ScrollView contentContainerStyle={{ padding: 20, gap: 14 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 12 }}><Pressable onPress={() => router.back()} style={{ padding: 8 }}><ChevronLeft color={theme.text} size={22} /></Pressable><View style={{ flex: 1 }}><Text style={{ color: theme.text, fontSize: 25, fontWeight: '900' }}>订阅与订单</Text><Text style={{ color: theme.subtext, marginTop: 3 }}>套餐和支付状态均来自服务端</Text></View><Pressable onPress={() => { void checkout.refetch(); void orders.refetch(); }} style={{ padding: 8 }}><RefreshCw color={theme.primary} size={19} /></Pressable></View>{checkout.error || orders.error ? <Text style={{ color: theme.danger }}>{humanizeApiError(checkout.error || orders.error)}</Text> : null}{actionError ? <Text style={{ color: theme.danger }}>{humanizeApiError(actionError)}</Text> : null}<View style={{ backgroundColor: theme.card, borderColor: theme.border, borderWidth: 1, borderRadius: 18, padding: 16 }}><Text style={{ color: theme.text, fontSize: 16, fontWeight: '900' }}>可购买套餐</Text>{checkout.isLoading ? <ActivityIndicator color={theme.primary} style={{ marginTop: 20 }} /> : checkout.data?.plans?.length ? <View style={{ gap: 9, marginTop: 12 }}>{checkout.data.plans.map((item) => <Pressable key={item.id} onPress={() => setPlan(item)} style={{ borderRadius: 14, borderWidth: 1, borderColor: plan?.id === item.id ? theme.primary : theme.border, backgroundColor: plan?.id === item.id ? theme.primarySoft : theme.cardRaised, padding: 13 }}><View style={{ flexDirection: 'row', alignItems: 'center' }}><View style={{ flex: 1 }}><Text style={{ color: theme.text, fontWeight: '900' }}>{item.name}</Text><Text style={{ color: theme.subtext, fontSize: 11, marginTop: 4 }} numberOfLines={2}>{item.description || item.product_name || '服务订阅套餐'}</Text></View><Text style={{ color: theme.primary, fontWeight: '900' }}>{item.currency || 'USD'} {item.price.toFixed(2)}</Text></View>{plan?.id === item.id ? <CheckCircle2 color={theme.primary} size={17} style={{ position: 'absolute', right: 10, top: 10 }} /> : null}</Pressable>)}</View> : <Text style={{ color: theme.subtext, marginTop: 14 }}>当前没有可售套餐</Text>}{plan ? <><Text style={{ color: theme.faint, fontSize: 11, marginTop: 14 }}>支付方式：{methods.length ? methods.join('、') : '当前没有可用支付方式'}</Text><Pressable disabled={create.isPending || methods.length === 0} onPress={() => create.mutate()} style={{ marginTop: 12, borderRadius: 14, paddingVertical: 13, backgroundColor: create.isPending || methods.length === 0 ? theme.muted : theme.primary, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 7 }}><CreditCard color="#fff" size={16} /><Text style={{ color: '#fff', fontWeight: '900' }}>{create.isPending ? '创建订单中…' : methods.length ? '创建支付订单' : '暂无可用支付方式'}</Text></Pressable></> : null}{create.error ? <Text style={{ color: theme.danger, marginTop: 10 }}>{humanizeApiError(create.error)}</Text> : null}</View>
    <View style={{ backgroundColor: theme.card, borderColor: theme.border, borderWidth: 1, borderRadius: 18, padding: 16 }}><Text style={{ color: theme.text, fontWeight: '900', fontSize: 16 }}>我的订单</Text>{orders.isLoading ? <ActivityIndicator color={theme.primary} style={{ marginTop: 20 }} /> : orders.data?.items?.length ? <View style={{ gap: 12, marginTop: 13 }}>{orders.data.items.map((order) => <OrderRow key={order.id} order={order} onCancel={() => Alert.alert('取消订单', '确认取消这个待支付订单？', [{ text: '返回', style: 'cancel' }, { text: '确认取消', style: 'destructive', onPress: () => cancel.mutate(order.id) }])} onVerify={() => verify.mutate(order)} />)}</View> : <Text style={{ color: theme.subtext, marginTop: 14 }}>暂无订单</Text>}</View>
  </ScrollView></View>;
}
function OrderRow({ order, onCancel, onVerify }: { order: PaymentOrder; onCancel: () => void; onVerify: () => void }) { const pending = ['pending', 'created', 'unpaid'].includes(order.status.toLowerCase()); const paid = ['paid', 'completed'].includes(order.status.toLowerCase()); return <View style={{ borderBottomWidth: 1, borderBottomColor: theme.border, paddingBottom: 11 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 9 }}><View style={{ width: 30, height: 30, borderRadius: 9, backgroundColor: paid ? theme.successSoft : pending ? theme.warningSoft : theme.cardRaised, alignItems: 'center', justifyContent: 'center' }}>{paid ? <CheckCircle2 color={theme.success} size={16} /> : pending ? <CreditCard color={theme.warning} size={16} /> : <XCircle color={theme.faint} size={16} />}</View><View style={{ flex: 1 }}><Text style={{ color: theme.text, fontWeight: '800' }}>#{order.out_trade_no || order.id}</Text><Text style={{ color: theme.subtext, fontSize: 11, marginTop: 3 }}>{order.created_at ? new Date(order.created_at).toLocaleString('zh-CN') : '--'} · {order.payment_type}</Text></View><Text style={{ color: theme.text, fontWeight: '900' }}>${Number(order.pay_amount ?? order.amount ?? 0).toFixed(2)}</Text></View>{pending ? <View style={{ flexDirection: 'row', gap: 8, marginTop: 9 }}><Pressable onPress={onVerify} style={{ flex: 1, borderRadius: 10, backgroundColor: theme.primarySoft, alignItems: 'center', paddingVertical: 9 }}><Text style={{ color: theme.primary, fontSize: 12, fontWeight: '800' }}>查询支付状态</Text></Pressable><Pressable onPress={onCancel} style={{ borderRadius: 10, backgroundColor: theme.dangerSoft, alignItems: 'center', paddingHorizontal: 14, paddingVertical: 9 }}><Text style={{ color: theme.danger, fontSize: 12, fontWeight: '800' }}>取消</Text></Pressable></View> : null}</View>; }
